### ISSUE TITLE
README needs an example

### ISSUE THREAD

**Issue by josephdburdick** [OlehZymnytskiy/foursquare#2]
Hi, I've tried to run this several ways but I keep getting back errors that I haven't passed arguments along correctly. Can you provide an example of a request using the params documentation from Foursquare? Thanks!

**Comment by jamielob** [comment]
I agree.  Happy to do this @OlehZymnytskiy  if you want to add me as a collaborator?

In the meantime here is an example for you:
```
var params = {};
params.query = 'Nopalito';
params.near = 'San Francisco, CA';
Foursquare.find(params, function(error, result) {
	console.log(result);
});
```

**Comment by josephdburdick** [comment]
Thanks so much @jamielob ! I'd fork and throw an example up but I couldn't figure out how to use this plugin so I created my own server-side method to handle it. :hammer:

**Comment by OlehZymnytskiy** [comment]
@jamielob, thanks
